### DISCUSSION TITLE
Print stylesheet

### DISCUSSION THREAD

**Discussion by trueberryless** [withastro/starlight#1160] [Feature Requests]
### What version of `starlight` are you using?

0.13.0

### What is your idea?

I don't know if it is possible to implement but it would be great to have the option to print one page at a time.  
Windows supports printing webpages out of the box but it looks kinda awkward:

![image](https://github.com/withastro/starlight/assets/99918022/a22eecb2-626a-4897-88bb-6f305d5f9f9a)

It would be great if the Windows integrated print option would be overriden to print only the headings and text without the webpage layout...

### Why is this feature necessary?

It is just nice to have.

### Participation

- [ ] I am willing to submit a pull request for this feature.

**Comment by HiDeoo** [comment]
This should be doable by shipping a [print style sheet](https://developer.mozilla.org/en-US/docs/Web/Guide/Printing#using_a_print_style_sheet).

If it's a common use-case for you, you can also already use [custom CSS](https://starlight.astro.build/guides/css-and-tailwind/#custom-css-styles) and a media query to target print.

For example, if I try to print right now the default template, I get something similar to your screenshot:

<img width="765" alt="SCR-20231128-klyd" src="https://github.com/withastro/starlight/assets/494699/8774918c-f310-42d2-a548-b551d04f3a25">

Using this custom CSS:

```css
@media print {
  .header,
  #starlight__sidebar,
  .right-sidebar-container,
  footer {
    display: none;
  }

  .main-frame {
    padding-inline-start: 0;
    padding-top: 0;
  }

  .main-pane {
    width: 100%;
    --sl-content-margin-inline: unset;
  }

  .sl-container {
    --sl-content-width: 100%;
  }
}
```

I get this:

<img width="764" alt="SCR-20231128-kpwh" src="https://github.com/withastro/starlight/assets/494699/e730c06a-1069-403c-80e2-92f26606a06e">
