### DISCUSSION TITLE
Allow to pass two colours to `Icon`

### DISCUSSION THREAD

**Discussion by ematipico** [withastro/starlight#1856] [Feature Requests]
### What version of `starlight` are you using?

0.22.1

### What is your idea?

Allow `Icon` to accept a `darkColor` and `lightColor` props. `darkColor` is applied when dark mode is active, and `lightColor` is applied when light mode is active.

 

### Why is this feature necessary?

At the moment `Icon` accepts a `color` attribute. However, when working with light and dark modes, a colour could fit one mode but not the other in terms of contract.

### Participation

- [ ] I am willing to submit a pull request for this feature.

**Comment by HiDeoo** [comment]
Sharing a slightly different approach that I personally use for this case with CSS custom properties which can be passed down to the `<Icon>` component.

1. Setup [custom styles](https://starlight.astro.build/guides/css-and-tailwind/#custom-css-styles) in Starlight.
2. Define a new custom property in my custom CSS file representing the color of the icon in both light and dark mode:

    ```css
    /* Colors (dark mode) */
    :root {
      --icon-color-red: hsl(359 82% 56%);
    }
    
    /* Colours (light mode) */
    :root[data-theme="light"] {
      --icon-color-red: hsl(359 86% 36%);
    }
    ```

3. Use the variable with the `<Icon>` component:

   ```mdx
   <Icon name="star" color="var(--icon-color-red)" size="4rem" />
   ```
