### DISCUSSION TITLE
Feature Request: Basic enhancements required

### DISCUSSION THREAD

**Discussion by fmunteanu** [withastro/starlight#1985] [Feature Requests]
### What version of `starlight` are you using?

0.24.0

### What is your idea?

Coming from Hugo, I find Astro combined with Starlight theme to bring several enhancements. However, I believe there are few basic but quite important neglected features, all related to Header.astro.

### Page Width

The current page format is unrealistic. Example:

![image](https://github.com/withastro/starlight/assets/19806136/a85ab2f4-fd02-4cee-84f9-a419163a7db3)

I had to add into custom CSS the following value, to address the format (which should be implemented by default):

```
:root {
  --sl-content-width: calc(100vw - 0.3 * var(--sl-sidebar-pad-x) - 2 * var(--sl-sidebar-width));
}
```

End-user should have the ability to:

- Define the content pages width expanding to 100%, following existing page design
- Define the overall  page width, which keeps the page elements proportional, see [example](https://axivo.com/k3s-cluster/wiki/) 

### Slots missing in Header.astro

I understand the Astro concept, allowing end-user to overwrite a specific component. Still, this forces developers to add modifications to source code, which can be easily fixed by adding slots into key Header.astro locations.

Proposed Header.astro slots:

- Ability to add links, similar to https://astro.build.
- Ability to add an additional `project` title, similar to https://docs.astro.build.
- Ability to sort the added elements by `weight`, right now is technically impossible to move for example the search bar next to `SocialIcons` without creating a completely custom  Header.astro file (blocker for new release versions). See below the Menus suggestion.

Example of search bar modification, requiring the creation of an entire Header.astro component, just to add `md:w-64 place-self-end` classes (I personally don't see why the search bar input exists, since there is a new popup opening, maybe is related to Algolia plugin behaviour, a simple 🔍 icon should suffice):

```
	<div class="sl-flex md:w-64 place-self-end">
		{shouldRenderSearch && <Search {...Astro.props} />}
	</div>
```

![image](https://github.com/withastro/starlight/assets/19806136/e79ef11d-780d-4571-b04f-364d1e14a1b9)

###  Menus

Right now there is no way in Starlight to define specific menus, to be used into specific sub-directories. Logic example in Hugo, `main` represents the ID associated, I can define additional menus, for example `menus.project` which will be displayed when I visit the `/docs/project` link (note the `weight`, allowing end-user to easily define the location/order of each menu parent category into header).

Hugo is also flexible with the displayed page link, by setting the `pageRef` to `/wiki` directory, while displaying the title `Documentation` into menu:

```
menus:
  main:
    - name: Documentation
      identifier: wiki
      pageRef: /wiki
      weight: 1
    - name: Tutorials
      identifier: tutorials
      pageRef: /tutorials
      weight: 2
    - name: Search
      params:
        type: search
      weight: 3
    - name: GitHub
      params:
        icon: github
      url: https://github.com/axivo/k3s-cluster
      weight: 4
    - name: Parent
      params:
        icon: folder
      url: ../
      weight: 5
  sidebar:
    - identifier: more
      name: More
      params:
        type: separator
      weight: 1
    - identifier: discussions
      name: "🌐 Discussions ↗"
      url: "https://github.com/axivo/k3s-cluster/discussions"
      weight: 2
    - identifier: issues
      name: "🌐 Issues ↗"
      url: "https://github.com/axivo/k3s-cluster/issues"
      weight: 3
```

From my perspective, all the above detailed points are important missing features in Astro Starlight.

### Why is this feature necessary?

See above explained details.

### Do you have examples of this feature in other projects?

[Hugo website](https://axivo.com/k3s-cluster/) which I intend to migrate to Starlight.

### Participation

- [ ] I am willing to submit a pull request for this feature.
