### DISCUSSION TITLE
Sidebar Icons

### DISCUSSION THREAD

**Discussion by jbergstroem** [withastro/starlight#2159] [Feature Requests]
### What version of `starlight` are you using?

0.25.3

### What is your idea?

It would be great if the sidebar items would optionally be drawn with icons. I guess this is harder to achieve with the autogenerated sidebar; but for us that set it manually it could be passed as an option to the `link` attribute in the `sidebar` config in `astro.config.mjs`.

### Why is this feature necessary?

It helps to visually organize the sidebar items.

### Do you have examples of this feature in other projects?

- [Medusa documentation](https://docs.medusajs.com)

### Participation

- [x] I am willing to submit a pull request for this feature.

**Comment by jbergstroem** [comment]
I am aware that this can be done via `attrs` (`class="myicon"` and `.myicon::before {}`) but it seems like a low hanging fruit since icons are well integrated elsewhere.

**Reply by matifali** [reply]
Looking into it

**Comment by ghost** [comment]
For anyone who needs to do this with the autogenerated sidebar:

```css
@font-face {
	font-family: "fontawesome";
	src: url("/fonts/fa-solid-900.woff2");
}

.messages-badge {
	font-family: "fontawesome";
	background: none;
	border: none;
}

ul.top-level .group-label {
	direction: rtl; /* If you want the icon on the left */
}
```

```ts
				{
					label: 'Messages',
					autogenerate: { directory: 'messages' },
					badge: {
						text: "", // Font awesome glyph
						class: "messages-badge"
					}
				},
```

It works pretty well with the downside of not being able to use the badge as a badge anymore. I would love to see this implemented officially..
