### DISCUSSION TITLE
Translations don't seem to apply to labels of link items in the sidebar

### DISCUSSION THREAD

**Discussion by novusnota** [withastro/starlight#2431] [Q&A] [answered]
Consider the following sidebar from `astro.config.mjs`:

```js
sidebar: [
  {
    label: 'Book',
    translations: { 'zh-CN': '图书' },
    link: '#', attrs: { class: 'sidebar-separator' }
  },
  // other entries
]
```

Where `sidebar-separator` is defined in the custom css as:

```css
/* Add a sidebar separator */
.sidebar-separator {
    margin-top: 1rem;
    font-weight: 600;
    pointer-events: none;
}
```

When I switch the language in the top bar, only the entries with external links stay the same (in their English variant) — all other [i18n-capable items](https://starlight.astro.build/guides/sidebar/#internationalization). Am I missing something, or that's not implemented yet / a bug?
