### DISCUSSION TITLE
Unable to apply custom badge style in production

### DISCUSSION THREAD

**Discussion by gorohoroh** [withastro/starlight#2602] [Q&A] [answered]
As suggested in the [docs](https://starlight.astro.build/guides/sidebar/#badge-variants-and-custom-styling), I have created custom badge styles to use in my sidebar.

My Starlight config contains a reference to a custom CSS file:

```javascript
            customCss: ['./src/styles/custom.css'],
```

The CSS file contains definitions for the 3 kinds of badges that I'm looking for:

```css
.badge-red {
    height: 1em;
    width: 1em;
    border-radius: 50%;
    background-color: #da4d4d;
}

.badge-yellow {
    height: 1em;
    width: 1em;
    border-radius: 50%;
    background-color: #e5d85b;
}

.badge-green {
    height: 1em;
    width: 1em;
    border-radius: 50%;
    background-color: #87ee81;
}
```

Badges are referenced in the sidebar configuration like this:

```javascript
                {
                    label: 'Why protect personal data?',
                    items: [
                        {slug: 'why-protect-personal-data/risks', badge: {text: "", class: "badge-yellow"}},
                    ],
                }
```

In development mode, the result is just what I expect it to be:

<img width="282" alt="image" src="https://github.com/user-attachments/assets/95db9c50-6085-4747-8909-cea1a979355f">

However, when building, I can see that both the border radius and the background color get overridden by Starlight's own styles:

<img width="279" alt="image" src="https://github.com/user-attachments/assets/831422d5-8b86-4a26-b08a-0de3ffb2911b">

Computed styles in dev tools are as follows:

<img width="874" alt="image" src="https://github.com/user-attachments/assets/25ca1786-ac67-46c6-ac47-c1742ecdd5d7">

What am I doing wrong? How can I prevent my styles from being overridden in production mode?
