### DISCUSSION TITLE
Hero: let title and tagline go full width if there is no image content

### DISCUSSION THREAD

**Discussion by olets** [withastro/starlight#958] [Feature Requests]
### What version of `starlight` are you using?

0.9.1

### What is your idea?

https://github.com/withastro/starlight/blob/def71050fbdb9ae514b0a7c24ed2455f055fe6bd/packages/starlight/components/Hero.astro#L103 doesn't take into account whether or not there is `image.file` or `image.html` content ([components/Hero.astro#L23-L33](https://github.com/withastro/starlight/blob/def71050fbdb9ae514b0a7c24ed2455f055fe6bd/packages/starlight/components/Hero.astro#L23-L33)). 

### Why is this feature necessary?

An image-less Hero's text is restricted to 7/11 of the component width, with blank space for the remaining 4/11.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by marcprux** [comment]
I was able to do this by overriding the custom CSS like so:

```css
/* Override hero for when there is no image */
.hero {
  grid-template-columns: 1fr;
}

.hero h1 {
  text-align: center;
  max-width: 100%;
}

.hero .tagline {
  text-align: center;
  max-width: 100%;
}

.hero .actions {
  justify-content: center;
  text-align: center;
  max-width: 100%;
}
```

It is an inelegant solution, but it works.
