### ISSUE TITLE
GH Pages Deployment has no styles

### ISSUE THREAD

**Issue by jpwallace22** [withastro/starlight#1262]
### What version of `starlight` are you using?

0.15.0

### What version of `astro` are you using?

4.0.1

### What package manager are you using?

yarn

### What operating system are you using?

Mac, Linux

### What browser are you using?

Chrome, Firefox

### Describe the Bug

When deploying to Github Pages my site has no styles and the links don't work. 

This is my workflow: 
Since I am using a monorepo I was forced to use my own action. I am building to `build` instead of `dist` because anything that is `.gitignore`d fails the artifact upload. 
```yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    name: Deploy Docs 📖
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: 'use node ${{ env.NODE_VERSION }}'
        uses: actions/setup-node@v3
        with:
          node-version: '${{ env.NODE_VERSION }}'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
``` 

This is the [site](https://jpwallace22.github.io/use-react-workers/) after it deploys. 

### Link to Minimal Reproducible Example

https://jpwallace22.github.io/use-react-workers/

### Participation

- [ ] I am willing to submit a pull request for this issue.
