### ISSUE TITLE
Display misplacement of @monaco-editor/react in starlight

### ISSUE THREAD

**Issue by HuakunShen** [withastro/starlight#1931]
### What version of `starlight` are you using?

0.23.1

### What version of `astro` are you using?

4.8.6

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Edge, Arc, Chrome

### Describe the Bug

Displaying react monaco editor in starlight has line misplacement. Not sure what is reason is, no error displayed.

The editor works in plain astro website, but not starlight.

![image](https://github.com/withastro/starlight/assets/33727687/842d0c6e-ef30-48ec-b2e5-f898a7c636e3)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-starlight-5zso9e?file=src%2Fcontent%2Fdocs%2Findex.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HuakunShen** [comment]
I also tried to include monaco-editor without the react wrapper. Got the same problem.

I also tried `@monaco-editor/react` in docusaurus, the display has no problem. 

# Comparison with Inspector

## Starlight

![image](https://github.com/withastro/starlight/assets/33727687/a4b1ddfe-5c08-4b6d-ad31-95b088763108)

## Docusaurus

![image](https://github.com/withastro/starlight/assets/33727687/96cb2886-b508-47a8-a5ba-079cd492402e)

**Comment by HuakunShen** [comment]
Problem solved by changing the margin top of this element from 1rem to 0rem. 

![image](https://github.com/withastro/starlight/assets/33727687/0b56afae-b1de-480b-bab3-debd9c575ee8)

So the patch to fix this is adding a custom css

```css
.sl-container.astro-stprhjhk > .sl-markdown-content :not(a, strong, em, del, span, input, code)+ :not(a, strong, em, del, span, input, code, :where(.not-content *)) {
    margin-top: 0rem;
}
```
