### ISSUE TITLE
Support deploy to GitHub Pages

### ISSUE THREAD

**Issue by torn4dom4n** [withastro/starlight#804]
### What version of `starlight` are you using?

0.10.4

### What is your idea?

Enable to deploy a site using Starlight to GitHub Pages using GitHub Actions

### Why is this feature necessary?

Astro supports deployment to GitHub Pages so I think this is a great idea.

### Do you have examples of this feature in other projects?

https://github.com/MedPocket/18-months

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by delucis** [comment]
This is possible already! Following the [GitHub pages deploy guide](https://docs.astro.build/en/guides/deploy/github/) in Astro’s docs should work for Starlight sites too. If it doesn’t, that’s a bug.

**Comment by delucis** [comment]
Ah yeah, you do still need to write links to include the base path, so in your hero config:

```yml
hero:
  tagline: Hành trình 18 tháng của Louis Nguyen.
  image:
    file: ../../assets/logo.svg
  actions:
    - text: Khám phá
      link: /18-months/nhat-ky/231003/
```

By the way, I see you have translated the UI into Vietnamese in that repo:
https://github.com/MedPocket/18-months/blob/c75d4082f43ca8cd7b8478bf52f56e83504f23ef/src/content/i18n/vi/vi.json

If you feel like submitting a PR adding that to Starlight for everyone to use, that would be much appreciated! We have guidance on how to do that here: https://github.com/withastro/starlight/blob/main/CONTRIBUTING.md#translations

You could also submit the Pagefind search translations to the Pagefind repo: https://github.com/CloudCannon/pagefind/tree/main/pagefind_ui/translations
