### ISSUE TITLE
Height and width of Embed element are not correct.

### ISSUE THREAD

**Issue by torn4dom4n** [withastro/starlight#937]
### What version of `starlight` are you using?

0.11.1

### What version of `astro` are you using?

v3.3.2

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### What browser are you using?

Edge

### Describe the Bug

The height and width are not correct with an embedded YouTube.

In this screen you can see height and width in my code differ from actual height and width.

![image](https://github.com/withastro/starlight/assets/27698189/4939cec9-d2c4-4538-8fe0-01729ffec3ea)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nfsqau?file=src%2Fcontent%2Fdocs%2Fguides%2Fexample.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by HiDeoo** [comment]
Thanks for the report.

The issue is due to [this CSS rule](https://github.com/withastro/starlight/blob/25ca5146463a190976335f7a7244f70c3b91e69a/packages/starlight/components/MarkdownContent.astro#L51-L55) applying `height: auto;` to some elements.

I have not yet experimented with a fix, but I guess we could only apply the height rule if the elements do not have a `height` attribute already or something like that.

**Comment by kevinzunigacuellar** [comment]
I was thinking something like this may work 

```css
.content :global(:is(img, picture, video, canvas, svg, iframe):not(:where(.not-content *))) {
    display: block;
    max-width: 100%;
}

.content :global(:is(img, picture, video, canvas, svg, iframe):not(:where(.not-content *))):not([height]) {
    height: auto;
}
```
